# See: https://golangci-lint.run/usage/configuration/
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - goimports
    - unused
    - errcheck
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace
