services:
  app:
    image: gotodo
    build:
      args:
        - target=dev
    volumes:
      - .:/app
    ports:
      - "18000:8080"
    # [air で実行するため不要]command: sh -c "go build -o ./tmp/main . && APP_ENV=dev APP_USER=air ./tmp/main 8080"